### ISSUE TITLE
Great HTML

### ISSUE THREAD

**Issue by Rodrigap** [AndreiR01/Tea-Cozy#1]
https://github.com/AndreiR01/Tea-Cozy/blob/d1422e84efda6a43d8bdfcf3b32507dc3d5735a9/index.html#L94-L108

Your HTML looks great! I love that you kept your indentation consistent and perfect and that you added in comments to help separate and label different code sections. My only critique is that you should eliminate the random chunks of whitespace in your code, like this big one here. Just a minor comment, but it'll help keep your code looking professional

**Comment by AndreiR01** [comment]
Thank you
