### ISSUE TITLE
CSS organization

### ISSUE THREAD

**Issue by Rodrigap** [AndreiR01/Tea-Cozy#3]
https://github.com/AndreiR01/Tea-Cozy/blob/d1422e84efda6a43d8bdfcf3b32507dc3d5735a9/css/style.css#L23-L37

Your CSS looks good, but remember to keep your spacing consistent. You should ideally have a single line of blank space between each CSS selector's code! Like this:

 ```
 align-items: center;
  margin-top: 0px;
  padding-top: 0px;
  width: 100%;
}

header img {
  height: 50px;
  padding-left: 10px;
}

nav span {
      display: inline-block;
      padding: 20px 10px;
  }
}

nav {
```

**Comment by AndreiR01** [comment]
Much appreciated
