### ISSUE TITLE
Grade: Meets Expectations

### ISSUE THREAD

**Issue by Rodrigap** [AndreiR01/Tea-Cozy#5]
Nice job on this project! Your HTML and CSS both look great, all your code is fully functional and well-organized. I especially love your HTML, it's really good to get into the habit of keeping all your indentation perfect and adding comments. Your CSS is also efficient and well-done, but I'd recommend adding some whitespace to break up the code, and you can always add comments if you'd like to make it even more organized! Your finished product looks great, it looks just like the spec! Remember that you're not limited to the spec, you're free to add extra sections or additional styling elements if you'd like to (colors, fonts, borders, animations, etc). Overall, great job!

**Comment by AndreiR01** [comment]
Thank you so much
